apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbucketevents.bwe.example.org
spec:
  group: bwe.example.org
  names:
    kind: XBucketEvents
    plural: xbucketevents
  claimNames:
    kind: BucketEvents
    plural: bucketevents
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object